### ISSUE TITLE
game crashes when opening the book in a server (1.16.4) neoforge 1.21.1 .83

### ISSUE THREAD

**Issue by VaporeonScripts** [Cazsius/Spice-of-Life-Carrot-Edition#166]
https://mclo.gs/CCrjIsI

**Comment by VaporeonScripts** [comment]
stacktrace:
https://mclo.gs/AG5Dhu5

**Comment by Mrbysco** [comment]
Can you confirm this issue without Sinytra Connector?

**Comment by VaporeonScripts** [comment]
not related to sinytra, already tested without it

**Comment by Mrbysco** [comment]
There's a boat load of mods in your instance, have you been able to narrow down which mod combination cause the issue to appear? As I am unable to reproduce it myself

**Comment by VaporeonScripts** [comment]
not yet, but i cant right now. also this only happens in a hosted SERVER, singleplayer works fine

**Comment by Temil2006** [comment]
to add to this post, I'm having the same issue with the book crashing the "client" ..however same as what the OP said, it only crashes the client if it's conencted to a server with the mod.. but single player works fine to open the book.

attached is my client crash log.
[crash-2024-12-01_17.21.45-client.txt](https://github.com/user-attachments/files/17970600/crash-2024-12-01_17.21.45-client.txt)

I also did a quick comparison between the logs OP provided and my server, and here is a list of the same mods between the 2 servers.. excluding the version numbers as the comparison level.. not sure if this helps at all.

this is rather hard to troubleshoot seeing as it doesn't happen is single player.. otherwise i would have narrowed it down .. trying to strip out mods from both server and client, a bit more problomatic.


[neoforge]ctov
accelerated-decay-neoforge
AdvancementPlaques
allthearcanistgear
allthemodium
almostunified-neoforge
AmbientSounds_NEOFORGE
ApothicAttributes
ApothicSpawners
appleskin-neoforge
Aquaculture
architectury
ars_additions
ars_nouveau
ars_ocultas
artifacts-neoforge
athena-neoforge
AutochefsDelight
bagus_lib
balm-neoforge
bettercombat-neoforge
BetterThirdPerson
bookshelf-neoforge
BridgingMod
champions-neoforge
chipped-neoforge
chunksending
cloth-config
collective
comforts-neoforge
common-networking-neoforge
Controlling-neoforge
cookingforblockheads-neoforge
Corgilib-NeoForge
coroutil-neoforge
craftingtweaks-neoforge
CreativeCore_NEOFORGE
Creeperoverhaul-neoforge
Cucumber
cupboard
deeperdarker-neoforge
DoggyTalentsNext
DungeonCrawl-NeoForge
DungeonsArise
DungeonsAriseSevenSeas
eccentrictome
endermanoverhaul-neoforge
endersdelight
entity_model_features_neoforge
entity_texture_features_neoforge
entityculling-neoforge
EquipmentCompare
eternalstarlight
expandeddelight
ExtremeSoundMuffler
FarmersDelight
farmingforblockheads-neoforge
ferritecore
flickerfix
forbidden_arcanus
FramedBlocks
friendsandfoes-neoforge
fruitsdelight
ftb-library-neoforge
fusion
fzzy_config
GatewaysToEternity
geckolib-neoforge
Glassential-renewed-neoforge
GlitchCore-neoforge
guardvillagers
Iceberg
InventoryProfilesNext-neoforge
iris-neoforge
irons_spellbooks
Jade
JadeAddons
jamlib-neoforge
jearchaeology
jei
justenoughbreeding-neoforge
JustEnoughProfessions-neoforge
konkrete_neoforge
LegendaryTooltips
libIPN-neoforge
lithostitched-neoforge
lootintegrations_ctov
lootintegrations_dungeoncrawl
lootintegrations_yungs
lootintegrations
lootr-neoforge
mcw-paths
modonomicon
MonsterPlus-NeoForge
moonlight
moredelight
morered
MutantMonsters
NaturesCompass
netherportalfix-neoforge
notenoughanimations-neoforge
Nullscape
occultism
OctoLib-NEOFORGE
Oh-The-Biomes-Weve-Gone
Oh-The-Trees-Youll-Grow
overloadedarmorbar-neoforge
ParCool
Placebo
player-animation-lib-forge
polymorph-neoforge
prickle-neoforge
Prism
projectvibrantjourneys
PuzzlesLib
rarcompat
rechiseled
rechiseled_chipped
recipeessentials
redstonepen
relics
repeatable_trial_vaults-neoforge
repurposed_structures
resourcefullib-neoforge
rhino
rightclickharvest-neoforge
RootsClassic
Searchables-neoforge
seasonhud-neoforge
SereneSeasons-neoforge
showcaseitem
silent-gear
silent-lib
solcarrot
sophisticatedbackpacks
sophisticatedcore
sophisticatedstorage
spark
smoothchunk
sodium-neoforge
sodiumoptionsapi-neoforge
StylishEffects
supermartijn642configlib
supermartijn642corelib
TerraBlender-neoforge
the_bumblezone
tombstone-neoforge
twilightdelight
twilightforest
txnilib-neoforge
valhelsia_core-neoforge
variantsandventures-neoforge
watut-neoforge
waystones-neoforge
wits
YungsApi
YungsBetterDesertTemples
YungsBetterDungeons
YungsBetterEndIsland
YungsBetterJungleTemples
YungsBetterMineshafts
YungsBetterNetherFortresses
YungsBetterOceanMonuments
YungsBetterStrongholds
YungsBetterWitchHuts
YungsBridges
YungsExtras

**Comment by Mrbysco** [comment]
The only reason I can see is if a mod is somehow stopping the PlayerLoggedInEvent from firing as that is used to sent a packet to people login in to trigger their client to build a list of foods.

I am unable to reproduce it with just SoL in either server or singleplayer

**Comment by Temil2006** [comment]
> The only reason I can see is if a mod is somehow stopping the PlayerLoggedInEvent from firing as that is used to sent a packet to people login in to trigger their client to build a list of foods.
> 
> I am unable to reproduce it with just SoL in either server or singleplayer

anything specific you want me to look for pertaining to "PlayerLoggedInEvent " or similar within the server logs to try and help point us to any issues?

**Comment by Mrbysco** [comment]
All I need is a minimal reproduction case, but I don't have the free time required to remove/re-add mods until the issue can be reproduced with a minimal setup

**Comment by Temil2006** [comment]
well, went through all the different mods and couldn't figure it out, so I went a different method... I placed only 2 mods on a test server and matched it with the client.
file 1 :: jei-1.21.1-neoforge-19.21.0.247.jar
file 2 :: solcarrot-1.21.1-1.16.4.jar

started the server, connected from client, went into creative mod to spawn in the book. Tried to use it, and got the same error. again, only on server not a single player.

My server is running on NeoForge 21.1.80 .. if ya want to provide me a repository, I can zip up and send you my test server files in full, or I can spin it up and provide you the IP,etc to allow you to connect and see the error, but don't think that will help ya much since you would get same error as we are.

I'm not sure why you wouldn't be getting the same error if you tested on server as you stated you can't duplicate. curious what is different with your server you tested this with.. if ya want to drop me your server config files, I can load them into mine, change the ports and try it as a 1-to-1 test .. just let me know what all you need from me.

EDIT :: as an added test, i was only using JEI to spawn in the item. after i spawned it in, i did an added test by spawning it in.. shutting everything down, and removing JEI as well.. started server up with only the 'SOL" mod file, and still same error on client/server ..but not on single player. So that eliminates JEI as the potential cause and unfortunately points to something with server and the SOL mod.

**Comment by Mrbysco** [comment]
A new version is being built, I was only able to reproduce this issue outside of dev environments

**Comment by Temil2006** [comment]
tested and confirmed working on test server and also on live server. thanks.
