### ISSUE TITLE
Client crash when eating any food. 

### ISSUE THREAD

**Issue by kantsche** [Cazsius/Spice-of-Life-Carrot-Edition#32]
Strange new crash. Can't pin down what it causes.

https://pastebin.com/kzYqEc9L

**Comment by juliand665** [comment]
which version are you using? (both mc and SoL)

**Comment by kantsche** [comment]
1.12.2  + solcarrot-1.12.2-1.3.2.jar

**Comment by juliand665** [comment]
Thanks for the info!

Additionally, it'd be helpful to know your configured food milestones (from the config file) and your current progress (output from /sizefoodlist) as well as whether you're playing singleplayer, LAN multiplayer, multiplayer on a local server, or multiplayer on an external server.

**Comment by juliand665** [comment]
Oh, and: which version of AppleCore (this mod's sole dependency) are you using? I have a hunch it's a problem with that.

**Comment by kantsche** [comment]
AppleCore-mc1.12.2-3.1.1.jar
Happens on multiplayer external server
Default config
0 Foods

Its just strange that it worked a while ago.. maybe some other mod updated and caused this?

**Comment by kantsche** [comment]
Oh well, the culprit is Oversaturation.. how did I overlook that.. XD

**Comment by juliand665** [comment]
You're right. Unfortunately, it looks like this is out of our control.

While we could apply a sort of band-aid fix to make it not crash, this would necessarily result in foods not being tracked properly, so we'd rather leave it up to Oversaturation/AppleCore to fix.

(In detail, what's happening is that the event AppleCore is providing to us has null rather than the player object, which likely happens because of some weird conflict between that and Oversaturation. The event-firing code is pretty close to where all kinds of unsafe injections have to happen to provide events, which is likely where the two mods conflict.)
