### ISSUE TITLE
Max health issue?

### ISSUE THREAD

**Issue by raindropworks** [Cazsius/Spice-of-Life-Carrot-Edition#41]
I really don't know if this is a configuration issue, an issue with SOL Carrot, another mod, or Vanilla MC at this point.  From my research, vanilla MC is supposed to be able to handle a maximum health value of 1024 (per Minecraft Wiki), and according to my NBT data from the server, I have a max of 182 (20 base, 26 from Cyclic, and 136 from SOL Carrot).  I'm using SilentChaos' Health Bar mod to confirm that my client is indeed registering 182.0 as max health.

The problem I'm running into is I can't stay above 180.5.  Anytime I try to go above, I start taking damage with nothing visibly contributing to it.  No enemies, no status indicators, and trying to drink milk or dying didn't change anything.

I figured I'd start here with bug reporting because this mod is the most likely to generate very high heart values of the mods on my server

https://cdn.discordapp.com/attachments/490026238287806464/519993842020384769/unknown.png - Screenshot of the max health section of my player's NBT data
https://youtu.be/3cloJzREKsI - quick video of effects when I try to eat to get past 180.5 health

**Comment by juliand665** [comment]
Hey! Thanks for the detailed bug report and sorry about the late reply. Having recently refactored the code responsible for adjusting your max health, I can conclusively say that we didn't (and still don't) cap health (be it current or maximum) in any way.

In order to find out what's causing this, I'd suggest creating a new instance with just this mod (and some nice way of viewing the hearts), configuring it to give you tons of hearts per milestone, and then eating a bit to see if the health is capped in the same way. After that, you can proceed to add more and more mods until the issue starts appearing, at which point you'll hopefully be able to pinpoint what caused it pretty quickly :)

**Comment by juliand665** [comment]
I'll actually close this for now; you can reopen if you figure out it's actually us, or just add a comment if you find out what caused it; you've got me curious!
