### ISSUE TITLE
crash on server side

### ISSUE THREAD

**Issue by KuroPeach** [Cazsius/Spice-of-Life-Carrot-Edition#45]
Crash on server side
forge-1.12.2-14.23.5.2815-universal.jar
solcarrot-1.12.2-1.3.4.jar
https://paste.ubuntu.com/p/ZdJPbJg37P/

**Comment by juliand665** [comment]
I'm not 100% sure, but this is probably because `ItemFoodBook`, whose instantiation is causing the error, directly imports and works with the `GuiFoodBook` object. This could probably be avoided by using something like `player.openGui(SOLCarrot.instance, GUI_ID, world, pos.getX(), pos.getY(), pos.getZ());` rather than `Minecraft.getMinecraft().displayGuiScreen(new GuiFoodBook(player));`

**Comment by SirAron111** [comment]
I have the same issue i think its a compat issue with the newest apple core mod version https://pastebin.com/Gnm3uUEL

**Comment by juliand665** [comment]
That's the same issue, all right. But it's not a compatibility issue; I fixed it already (hence the issue being closed). This fix will be in the next update :)
