### ISSUE TITLE
Doesn't register: eaten carrot cake (pam's harvestcraft)

### ISSUE THREAD

**Issue by usafphoenix** [Cazsius/Spice-of-Life-Carrot-Edition#67]
some cakes from pam's harvestcraft don't register as having been eaten. noticed this particularly with carrot cake. 

Regular cheesecake, holiday cake and pumpkin cheese cake seem to work, but carrot cake, and cherry cheese cake don't register. May also have issues with some other new foods.

**Comment by juliand665** [comment]
Huh, interesting. And apart from the recipe/texture (and food values, perhaps?) they all behave exactly the same?

**Comment by usafphoenix** [comment]
My intuition says that it might be that it's a placed item that is being
right clicked in world to eat or it may be related to the no check cost
that cake has but I don't know

**Comment by juliand665** [comment]
Interesting, I just got around to testing it and every cake got registered correctly, so trying it increased your food count, but the only cake that updated the tooltip is pumpkin cake. However, pumpkin cake had its own problem where eating it would cause the item to show up twice in the food book, while the other cakes wouldn't show up at all.

Now, thanks for reporting it, but this issue isn't really major enough to warrant an update to the mod, especially since we've now moved on to 1.14, which probably doesn't present such issues anymore. I hope that's okay!
