### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Americannoli** [Cazsius/Spice-of-Life-Carrot-Edition#70]
A player can't connect to my server as it disconnects him saying:
[latest.log](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/3667630/latest.log)

**Comment by juliand665** [comment]
Thanks for the report! The log was a great start, but there's not much we can do without additional information. In order to fix a bug, the first step is always for us to reproduce it locally, and we can't do that based just on the information you've provided so far. Next steps:
- Does it happen for everyone on the server or just this one player?
- Does it still happen with just SoL: Carrot and AppleCore enabled? If not, which other mods need to be present for it to break?  
(A good way to figure this out would be to remove chunks of mods until it stops breaking, at which point you've narrowed it down to that chunk having the incompatible mod. Rinse and repeat until you've singled out the cause.)

**Comment by Americannoli** [comment]
It happened to a single player, I ended up deleting all of his player files rather than spending time on chunks. I appreciate the time though!
