### ISSUE TITLE
[1.14.4] Player returns from the end crash (using the clone event)

### ISSUE THREAD

**Issue by HyCraftHD** [Cazsius/Spice-of-Life-Carrot-Edition#72]
Crash. (Tested 1.14.4-1.9.2 / 1.14.4-1.9.3 from #71 
Forge version: 28.1.61
https://gist.github.com/HyCraftHD/4541ea16757f404e160db5b3832719e4
Might be duplicate of #71 

Occur when a player returns from the end. (The server crashes)
Sometimes occur when a new player joins the world.

The problem ist here: The original player has no capability
https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/febddbcd24bc72f6b6ef84d1833ef7816f8bed69/src/main/java/com/cazsius/solcarrot/tracking/CapabilityHandler.java#L55

**Comment by juliand665** [comment]
Thanks for the report!

In case you're curious, it's actually a forge bug: the event this is occurring in is explicitly intended for copying capabilities (data mods can attach), but that's impossible in this case because the original player to copy from is dead and thus its capabilities are disabled, so currently the easiest workaround is to "revive" the old player entity to access its data.

This might actually have something to do with #71; I'll have to see when ProsperCraft responds so we can resolve that too.

**Comment by juliand665** [comment]
fixed in [1.9.3](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2813746)!

**Comment by HyCraftHD** [comment]
Thanks 👍 
Keep up the good work!
