### ISSUE TITLE
Mod Pack claims this as a crash issue

### ISSUE THREAD

**Issue by RepoDraghon** [Cazsius/Spice-of-Life-Carrot-Edition#82]
[New Text Document.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4315275/New.Text.Document.txt)
![Screenshot (33)](https://user-images.githubusercontent.com/8423696/76367668-ef025c00-62ea-11ea-9798-79dd08829be8.png)

**Comment by juliand665** [comment]
oh yeah, looks like another instance of #80. I'll look into it.

**Comment by warderbrad** [comment]
I don't know if this is related but I am playing the MC Eternal modpack. Everything works fine until I try and look at the food book. When I do it crashes. We had thought it was due to eating a food item that had later been removed, this was ruled out (at least to us) when we had a new player join and try the book, it crashed his as well. Since he hadn't eaten any foods yet it would not be an issue. That is unless the book was trying to display the previously available food item as a to be eaten one. Our thought is that if there is a list of foods that can be eaten and it is checking that list but one of the food items was removed it could cause errors.

**Comment by juliand665** [comment]
@warderbrad _probably_ not related, but there's no way for us to know without a crash report or logs. Please collect those and open an issue—that sounds pretty bad.

**Comment by Ak4suke** [comment]
Happened to me when I tried to remove wheat from edible food in harvest craft config file. When I switched it back in, it solved the issue.
Any idea how to remove edible food from your config without crashing your save ?

You can find a crash report for the exact same thing as stated in the opening post.

[crash-2020-05-11_17.56.12-server.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/4610791/crash-2020-05-11_17.56.12-server.txt)

**Comment by Ak4suke** [comment]
Did a little of troubleshooting and found a way to bypass the issue but it has a cost.
Cleared my eaten list, modified my config in order to remove an edible and eaten food and it loads perfectly after that.
Seems that you can't remove an eaten food from your game without crashing your save.

**Comment by juliand665** [comment]
Thanks for the investigation, @Ak4suke! You came to exactly the right conclusion. I've fixed this locally and will be pushing out an update (1.8.4) very soon :)

**Comment by juliand665** [comment]
Officially approved on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/files/2959847).
